### ISSUE TITLE
Underscores and dashes in video IDs

### ISSUE THREAD

**Issue by favonia** [kong0107/yout-redirect#1]
It's possible to have underscores and dashes in video IDs. (I did not run the script, just checking the code for fun.)

https://github.com/kong0107/yout-redirect/blob/5b17bfd9f5e4d0a8b405d9932c5af9c996a6d123/background.js#L4

**Comment by kong0107** [comment]
`\w` matches underscores, but I did forget about dashes.
Thanks for reminding!
